services:
  db:
    image: postgres:15
    container_name: misuperpostgre
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-misuper_usuario}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
      POSTGRES_DB: ${POSTGRES_DB:-misuper_bd}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-misuper_usuario} -d ${POSTGRES_DB:-misuper_bd} -q"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack-server:latest
    container_name: misuperredis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: misuperapi
    restart: always
    command: >
      sh -c "sleep 10 &&
             poetry run alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
      - ./content:/app/content
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  wordpress_service:
    image: wordpress:latest
    container_name: wordpress_misuperprofe
    restart: always
    ports:
      - "8081:80" # Puerto 8081 del host mapeado al puerto 80 del contenedor WordPress
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-db_wordpress_service:3306}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wp_user}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wp_password}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress_db}
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL:-https://misuperprofe.com}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
    volumes:
      - wordpress_data:/var/www/html
      # - ./wp-content/plugins:/var/www/html/wp-content/plugins # LÍNEA COMENTADA/ELIMINADA
      - ./php-jwt-library:/var/www/html/wp-content/libs/php-jwt
    depends_on:
      - db_wordpress_service

  db_wordpress_service:
    image: mariadb:latest
    container_name: mariadb_misuperprofe
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress_db}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wp_user}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wp_password}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  postgres_data:
  wordpress_data:
  mariadb_data:
