"""add_area_to_external_user_map

Revision ID: 0ee49cca1552
Revises: 54b89d601461
Create Date: 2025-07-28 18:20:56.146926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee49cca1552'
down_revision: Union[str, None] = '54b89d601461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    area_enum = sa.Enum('A', 'B', 'C', 'D', 'E', name='areaenum')
    area_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('attempts', 'question_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('attempts', 'topic',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('external_user_map', sa.Column('area', area_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_user_map', 'area')
    op.alter_column('attempts', 'topic',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('attempts', 'question_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    area_enum = sa.Enum('A', 'B', 'C', 'D', 'E', name='areaenum')
    area_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
