"""Initial clean migration

Revision ID: 54b89d601461
Revises: 
Create Date: 2025-06-13 20:49:37.272799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b89d601461'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('achievement_type', sa.String(length=64), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('details', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_log_user_id_hash'), 'achievements_log', ['user_id_hash'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_user_id_hash'), 'attempts', ['user_id_hash'], unique=False)
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_curso_codigo'), 'curso', ['codigo'], unique=True)
    op.create_index(op.f('ix_curso_id'), 'curso', ['id'], unique=False)
    op.create_table('external_user_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_user_identifier', sa.String(), nullable=False),
    sa.Column('internal_user_id_hash', sa.String(), nullable=True),
    sa.Column('assigned_misuperprofe_role', sa.Enum('ALUMNO', 'PROFESOR', 'ADMIN_ACADEMIA', name='misuperproferole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_user_map_external_user_identifier'), 'external_user_map', ['external_user_identifier'], unique=True)
    op.create_index(op.f('ix_external_user_map_id'), 'external_user_map', ['id'], unique=False)
    op.create_index(op.f('ix_external_user_map_internal_user_id_hash'), 'external_user_map', ['internal_user_id_hash'], unique=True)
    op.create_table('growth_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_type', sa.String(length=32), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_log_prompt_type'), 'growth_log', ['prompt_type'], unique=False)
    op.create_index(op.f('ix_growth_log_user_id_hash'), 'growth_log', ['user_id_hash'], unique=False)
    op.create_table('grupo_clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_clase', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo_clase', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_clase_codigo_clase'), 'grupo_clase', ['codigo_clase'], unique=True)
    op.create_index(op.f('ix_grupo_clase_id'), 'grupo_clase', ['id'], unique=False)
    op.create_index(op.f('ix_grupo_clase_nombre_clase'), 'grupo_clase', ['nombre_clase'], unique=False)
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesor_email'), 'profesor', ['email'], unique=True)
    op.create_index(op.f('ix_profesor_id'), 'profesor', ['id'], unique=False)
    op.create_table('streaks',
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('current_days', sa.Integer(), nullable=True),
    sa.Column('longest_days', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id_hash')
    )
    op.create_table('student_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.String(length=255), nullable=False),
    sa.Column('student_user_id', sa.String(length=255), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_user_id', 'student_user_id', name='unique_teacher_student')
    )
    op.create_index(op.f('ix_student_assignments_id'), 'student_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_student_assignments_student_user_id'), 'student_assignments', ['student_user_id'], unique=False)
    op.create_index(op.f('ix_student_assignments_teacher_user_id'), 'student_assignments', ['teacher_user_id'], unique=False)
    op.create_table('teacher_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_roles_id'), 'teacher_roles', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_roles_user_id'), 'teacher_roles', ['user_id'], unique=True)
    op.create_table('user_progress',
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('hearts', sa.Integer(), nullable=True),
    sa.Column('chests', sa.Integer(), nullable=True),
    sa.Column('achievements', sa.String(length=512), nullable=True),
    sa.Column('theta', sa.Numeric(precision=5, scale=3), server_default='0.0', nullable=False),
    sa.PrimaryKeyConstraint('user_id_hash', 'course')
    )
    op.create_table('capitulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido_md', sa.Text(), nullable=False),
    sa.Column('contenido_html', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('beta_difficulty', sa.Numeric(precision=5, scale=3), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capitulo_id'), 'capitulo', ['id'], unique=False)
    op.create_table('grupo_clase_alumno_association',
    sa.Column('grupo_clase_id', sa.Integer(), nullable=False),
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_clase_id'], ['grupo_clase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_clase_id', 'user_id_hash')
    )
    op.create_index(op.f('ix_grupo_clase_alumno_association_user_id_hash'), 'grupo_clase_alumno_association', ['user_id_hash'], unique=False)
    op.create_table('grupo_clase_curso_association',
    sa.Column('grupo_clase_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_clase_id'], ['grupo_clase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_clase_id', 'curso_id')
    )
    op.create_table('profesor_grupo_clase_association',
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('grupo_clase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_clase_id'], ['grupo_clase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profesor_id', 'grupo_clase_id')
    )
    op.create_table('lesson_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('lesson_xp', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('items_completed', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Numeric(), nullable=True),
    sa.Column('current_session_streak', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['capitulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_sessions_course'), 'lesson_sessions', ['course'], unique=False)
    op.create_index(op.f('ix_lesson_sessions_user_id_hash'), 'lesson_sessions', ['user_id_hash'], unique=False)
    op.create_table('progress_units',
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('NO_INICIADO', 'EN_PROGRESO', 'COMPLETADO', name='userchapterstatus'), nullable=True),
    sa.Column('porcentaje', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['capitulo.id'], ),
    sa.PrimaryKeyConstraint('user_id_hash', 'chapter_id')
    )
    op.create_table('resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.String(length=100), nullable=False),
    sa.Column('capitulo_id', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.String(length=1), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('pregunta_generada', sa.Text(), nullable=True),
    sa.Column('respuesta_usuario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultado_id'), 'resultado', ['id'], unique=False)
    op.create_table('spaced_repetition',
    sa.Column('user_id_hash', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('times_incorrect', sa.Integer(), nullable=True),
    sa.Column('easiness_factor', sa.Numeric(precision=4, scale=2), server_default='2.5', nullable=False),
    sa.Column('repetition_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_interval_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_due', sa.DateTime(), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['capitulo.id'], ),
    sa.PrimaryKeyConstraint('user_id_hash', 'item_id', name='pk_spaced_repetition')
    )
    op.create_table('errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['lesson_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errors_session_id'), 'errors', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_errors_session_id'), table_name='errors')
    op.drop_table('errors')
    op.drop_table('spaced_repetition')
    op.drop_index(op.f('ix_resultado_id'), table_name='resultado')
    op.drop_table('resultado')
    op.drop_table('progress_units')
    op.drop_index(op.f('ix_lesson_sessions_user_id_hash'), table_name='lesson_sessions')
    op.drop_index(op.f('ix_lesson_sessions_course'), table_name='lesson_sessions')
    op.drop_table('lesson_sessions')
    op.drop_table('profesor_grupo_clase_association')
    op.drop_table('grupo_clase_curso_association')
    op.drop_index(op.f('ix_grupo_clase_alumno_association_user_id_hash'), table_name='grupo_clase_alumno_association')
    op.drop_table('grupo_clase_alumno_association')
    op.drop_index(op.f('ix_capitulo_id'), table_name='capitulo')
    op.drop_table('capitulo')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_teacher_roles_user_id'), table_name='teacher_roles')
    op.drop_index(op.f('ix_teacher_roles_id'), table_name='teacher_roles')
    op.drop_table('teacher_roles')
    op.drop_index(op.f('ix_student_assignments_teacher_user_id'), table_name='student_assignments')
    op.drop_index(op.f('ix_student_assignments_student_user_id'), table_name='student_assignments')
    op.drop_index(op.f('ix_student_assignments_id'), table_name='student_assignments')
    op.drop_table('student_assignments')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_profesor_id'), table_name='profesor')
    op.drop_index(op.f('ix_profesor_email'), table_name='profesor')
    op.drop_table('profesor')
    op.drop_index(op.f('ix_grupo_clase_nombre_clase'), table_name='grupo_clase')
    op.drop_index(op.f('ix_grupo_clase_id'), table_name='grupo_clase')
    op.drop_index(op.f('ix_grupo_clase_codigo_clase'), table_name='grupo_clase')
    op.drop_table('grupo_clase')
    op.drop_index(op.f('ix_growth_log_user_id_hash'), table_name='growth_log')
    op.drop_index(op.f('ix_growth_log_prompt_type'), table_name='growth_log')
    op.drop_table('growth_log')
    op.drop_index(op.f('ix_external_user_map_internal_user_id_hash'), table_name='external_user_map')
    op.drop_index(op.f('ix_external_user_map_id'), table_name='external_user_map')
    op.drop_index(op.f('ix_external_user_map_external_user_identifier'), table_name='external_user_map')
    op.drop_table('external_user_map')
    op.drop_index(op.f('ix_curso_id'), table_name='curso')
    op.drop_index(op.f('ix_curso_codigo'), table_name='curso')
    op.drop_table('curso')
    op.drop_index(op.f('ix_attempts_user_id_hash'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_achievements_log_user_id_hash'), table_name='achievements_log')
    op.drop_table('achievements_log')
    # ### end Alembic commands ###